DEFAULT_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'

DEFAULT_CLIENT_SERVICE_URLS = (
    'translate.googleapis.com',
)

DEFAULT_SERVICE_URLS = ('translate.google.ac', 'translate.google.ad', 'translate.google.ae',
                        'translate.google.al', 'translate.google.am', 'translate.google.as',
                        'translate.google.at', 'translate.google.az', 'translate.google.ba',
@@ -21,21 +25,21 @@
                        'translate.google.com.ai', 'translate.google.com.ar', 'translate.google.com.au',
                        'translate.google.com.bd', 'translate.google.com.bh', 'translate.google.com.bn',
                        'translate.google.com.bo', 'translate.google.com.br', 'translate.google.com.bz',
                        'translate.google.com.co', 'translate.google.com.cu', 'translate.google.com.cy', 
                        'translate.google.com.do', 'translate.google.com.ec', 'translate.google.com.eg', 
                        'translate.google.com.et', 'translate.google.com.fj', 'translate.google.com.gh', 
                        'translate.google.com.gi', 'translate.google.com.gt', 'translate.google.com.hk', 
                        'translate.google.com.jm', 'translate.google.com.kh', 'translate.google.com.kw', 
                        'translate.google.com.lb', 'translate.google.com.ly', 'translate.google.com.mm', 
                        'translate.google.com.mt', 'translate.google.com.mx', 'translate.google.com.my', 
                        'translate.google.com.na', 'translate.google.com.ng', 'translate.google.com.ni', 
                        'translate.google.com.np', 'translate.google.com.om', 'translate.google.com.pa', 
                        'translate.google.com.pe', 'translate.google.com.pg', 'translate.google.com.ph', 
                        'translate.google.com.pk', 'translate.google.com.pr', 'translate.google.com.py', 
                        'translate.google.com.qa', 'translate.google.com.sa', 'translate.google.com.sb', 
                        'translate.google.com.sg', 'translate.google.com.sl', 'translate.google.com.sv', 
                        'translate.google.com.tj', 'translate.google.com.tr', 'translate.google.com.tw', 
                        'translate.google.com.ua', 'translate.google.com.uy', 'translate.google.com.vc', 
                        'translate.google.com.co', 'translate.google.com.cu', 'translate.google.com.cy',
                        'translate.google.com.do', 'translate.google.com.ec', 'translate.google.com.eg',
                        'translate.google.com.et', 'translate.google.com.fj', 'translate.google.com.gh',
                        'translate.google.com.gi', 'translate.google.com.gt', 'translate.google.com.hk',
                        'translate.google.com.jm', 'translate.google.com.kh', 'translate.google.com.kw',
                        'translate.google.com.lb', 'translate.google.com.ly', 'translate.google.com.mm',
                        'translate.google.com.mt', 'translate.google.com.mx', 'translate.google.com.my',
                        'translate.google.com.na', 'translate.google.com.ng', 'translate.google.com.ni',
                        'translate.google.com.np', 'translate.google.com.om', 'translate.google.com.pa',
                        'translate.google.com.pe', 'translate.google.com.pg', 'translate.google.com.ph',
                        'translate.google.com.pk', 'translate.google.com.pr', 'translate.google.com.py',
                        'translate.google.com.qa', 'translate.google.com.sa', 'translate.google.com.sb',
                        'translate.google.com.sg', 'translate.google.com.sl', 'translate.google.com.sv',
                        'translate.google.com.tj', 'translate.google.com.tr', 'translate.google.com.tw',
                        'translate.google.com.ua', 'translate.google.com.uy', 'translate.google.com.vc',
                        'translate.google.com.vn', 'translate.google.com', 'translate.google.cv',
                        'translate.google.cz', 'translate.google.de', 'translate.google.dj',
                        'translate.google.dk', 'translate.google.dm', 'translate.google.dz',
@@ -65,9 +69,9 @@
                        'translate.google.st', 'translate.google.td', 'translate.google.tg',
                        'translate.google.tk', 'translate.google.tl', 'translate.google.tm',
                        'translate.google.tn', 'translate.google.to', 'translate.google.tt',
                        'translate.google.us', 'translate.google.vg', 'translate.google.vu', 
                        'translate.google.us', 'translate.google.vg', 'translate.google.vu',
                        'translate.google.ws')
                        

SPECIAL_CASES = {
    'ee': 'et',
}
@@ -78,10 +82,14 @@
    'am': 'amharic',
    'ar': 'arabic',
    'hy': 'armenian',
    'as': 'assamese',
    'ay': 'aymara',
    'az': 'azerbaijani',
    'bm': 'bambara',
    'eu': 'basque',
    'be': 'belarusian',
    'bn': 'bengali',
    'bho': 'bhojpuri',
    'bs': 'bosnian',
    'bg': 'bulgarian',
    'ca': 'catalan',
@@ -93,10 +101,13 @@
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'dv': 'dhivehi',
    'doi': 'dogri',
    'nl': 'dutch',
    'en': 'english',
    'eo': 'esperanto',
    'et': 'estonian',
    'ee': 'ewe',
    'tl': 'filipino',
    'fi': 'finnish',
    'fr': 'french',
@@ -105,6 +116,7 @@
    'ka': 'georgian',
    'de': 'german',
    'el': 'greek',
    'gn': 'guarani',
    'gu': 'gujarati',
    'ht': 'haitian creole',
    'ha': 'hausa',
@@ -116,6 +128,7 @@
    'hu': 'hungarian',
    'is': 'icelandic',
    'ig': 'igbo',
    'ilo': 'ilocano',
    'id': 'indonesian',
    'ga': 'irish',
    'it': 'italian',
@@ -124,35 +137,47 @@
    'kn': 'kannada',
    'kk': 'kazakh',
    'km': 'khmer',
    'gom': 'konkani',
    'ko': 'korean',
    'kri': 'krio',
    'ku': 'kurdish (kurmanji)',
    'ckb': 'kurdish (sorani)',
    'ky': 'kyrgyz',
    'lo': 'lao',
    'la': 'latin',
    'lv': 'latvian',
    'ln': 'lingala',
    'lt': 'lithuanian',
    'lg': 'luganda',
    'lb': 'luxembourgish',
    'mk': 'macedonian',
    'mai': 'maithili',
    'mg': 'malagasy',
    'ms': 'malay',
    'ml': 'malayalam',
    'mt': 'maltese',
    'mi': 'maori',
    'mr': 'marathi',
    'mni-M tei': 'meiteilon (manipuri)',
    'lus': 'mizo',
    'mn': 'mongolian',
    'my': 'myanmar (burmese)',
    'ne': 'nepali',
    'no': 'norwegian',
    'or': 'odia',
    'om': 'oromo',
    'ps': 'pashto',
    'fa': 'persian',
    'pl': 'polish',
    'pt': 'portuguese',
    'pa': 'punjabi',
    'qu': 'quechua',
    'ro': 'romanian',
    'ru': 'russian',
    'sm': 'samoan',
    'sa': 'sanskrit',
    'gd': 'scots gaelic',
    'nso': 'sepedi',
    'sr': 'serbian',
    'st': 'sesotho',
    'sn': 'shona',
@@ -169,7 +194,10 @@
    'ta': 'tamil',
    'te': 'telugu',
    'th': 'thai',
    'ti': 'tigrinya',
    'ts': 'tsonga',
    'tr': 'turkish',
    'ak': 'twi',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'ug': 'uyghur',
@@ -179,7 +207,7 @@
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'zu': 'zulu',
    'zu': 'zulu'
}

LANGCODES = dict(map(reversed, LANGUAGES.items()))
